language: bash
# non sudo will be a faster container-based build.
# but for now, we need sudo for installing shellcheck.
sudo: required

git:
  depth: 2
  submodules: false

before_install:
  - wget https://storage.googleapis.com/shellcheck/shellcheck-latest.linux.x86_64.tar.xz -O /tmp/shellcheck-latest.tar.xz
  - tar -xvf /tmp/shellcheck-latest.tar.xz
  - export PATH=$PWD/shellcheck-latest/:$PATH
  - which shellcheck
  - shellcheck -V

script: ./bin/lint.sh

notifications:
  email: false