cask_args appdir: "~/Applications", fontdir: "~/Library/Fonts"

tap "homebrew/services"
tap "caskroom/cask"
tap "caskroom/versions"

# cli
brew "mas"
brew "hub"
brew "wifi-password"
brew "youtube-dl"
cask "ngrok"

# code tools
brew "git"
brew "zsh"
brew "ag"
brew "jq"
brew "tree"
brew "pstree"
brew "wget"
brew "wrk"
brew "shellcheck"

# coding
brew "exercism"
cask "visual-studio-code"
cask "hyper"

# browsers
cask "google-chrome"
cask "firefox-developer-edition"

# others
cask "daisydisk"
cask "skype"